// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefineryContractAPI.Data;

#nullable disable

namespace RefineryContractAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefineryContractAPI.Models.AmandemenKontrak", b =>
                {
                    b.Property<string>("IdAmandemen")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_amandemen");

                    b.Property<string>("AlasanPerubahan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alasan_perubahan");

                    b.Property<string>("AmendmentDocuments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amendment_documents");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurasiAmandemen")
                        .HasColumnType("int")
                        .HasColumnName("durasi_amandemen");

                    b.Property<string>("IdKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_kontrak");

                    b.Property<string>("JenisAmandemen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis_amandemen");

                    b.Property<decimal?>("NilaiKontrakBaru")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nilai_kontrak_baru");

                    b.Property<string>("NoAmandemen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_amandemen");

                    b.Property<int>("NomorUrut")
                        .HasColumnType("int")
                        .HasColumnName("nomor_urut");

                    b.Property<DateTime?>("TanggalAmandemen")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_amandemen");

                    b.Property<DateTime?>("TanggalMulaiBaru")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_mulai_baru");

                    b.Property<DateTime?>("TanggalSelesaiBaru")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_selesai_baru");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdAmandemen");

                    b.HasIndex("IdKontrak");

                    b.ToTable("amandemen_kontrak", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.KonfigurasiSistem", b =>
                {
                    b.Property<string>("IdSetting")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_setting");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("NamaSetting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_setting");

                    b.Property<string>("NilaiSetting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nilai_setting");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdSetting");

                    b.ToTable("konfigurasi_sistem", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Kontrak", b =>
                {
                    b.Property<string>("IdKontrak")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_kontrak");

                    b.Property<string>("AktivitasSaatIni")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("aktivitas_saat_ini");

                    b.Property<string>("AlasanPerubahan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alasan_perubahan");

                    b.Property<string>("AmendmentDocuments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amendment_documents");

                    b.Property<string>("ContractDocuments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_documents");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DireksiPekerjaan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direksi_pekerjaan");

                    b.Property<string>("Disiplin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("disiplin");

                    b.Property<int?>("DurasiAmandemen")
                        .HasColumnType("int")
                        .HasColumnName("durasi_amandemen");

                    b.Property<int?>("DurasiKontrakHari")
                        .HasColumnType("int")
                        .HasColumnName("durasi_kontrak_hari");

                    b.Property<DateTime>("EstimasiTanggalKom")
                        .HasColumnType("datetime2")
                        .HasColumnName("estimasi_tanggal_kom");

                    b.Property<bool>("HasAmendment")
                        .HasColumnType("bit")
                        .HasColumnName("has_amendment");

                    b.Property<string>("IdVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_vendor");

                    b.Property<string>("JenisAmandemen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis_amandemen");

                    b.Property<string>("JudulKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul_kontrak");

                    b.Property<string>("Kendala")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kendala");

                    b.Property<bool>("KomTerlambat")
                        .HasColumnType("bit")
                        .HasColumnName("kom_terlambat");

                    b.Property<decimal?>("NilaiAwal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nilai_awal");

                    b.Property<decimal?>("NilaiKontrakBaru")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nilai_kontrak_baru");

                    b.Property<string>("NoAmandemen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_amandemen");

                    b.Property<string>("NoDokumenKontrak")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_dokumen_kontrak");

                    b.Property<string>("NoPoPr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_po_pr");

                    b.Property<double?>("ProgressActual")
                        .HasColumnType("float")
                        .HasColumnName("progress_actual");

                    b.Property<double?>("ProgressPlan")
                        .HasColumnType("float")
                        .HasColumnName("progress_plan");

                    b.Property<string>("SCurveData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("s_curve_data");

                    b.Property<int>("SlaKomHari")
                        .HasColumnType("int")
                        .HasColumnName("sla_kom_hari");

                    b.Property<string>("StatusKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_kontrak");

                    b.Property<DateTime?>("TanggalAmandemen")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_amandemen");

                    b.Property<DateTime?>("TanggalKom")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_kom");

                    b.Property<DateTime?>("TanggalLkp")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_lkp");

                    b.Property<DateTime?>("TanggalMaksimalKom")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_maksimal_kom");

                    b.Property<DateTime?>("TanggalMulai")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_mulai");

                    b.Property<DateTime?>("TanggalMulaiBaru")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_mulai_baru");

                    b.Property<DateTime?>("TanggalSelesai")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_selesai");

                    b.Property<DateTime?>("TanggalSelesaiBaru")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_selesai_baru");

                    b.Property<DateTime>("TanggalSpbDiterima")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_spb_diterima");

                    b.Property<DateTime?>("TanggalTerimaDokumen")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_terima_dokumen");

                    b.Property<string>("TipeKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe_kontrak");

                    b.Property<double?>("TkdnPercentage")
                        .HasColumnType("float")
                        .HasColumnName("tkdn_percentage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdKontrak");

                    b.HasIndex("IdVendor");

                    b.ToTable("kontrak", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.MonitoringLtsa", b =>
                {
                    b.Property<string>("IdLog")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_log");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<double>("DurasiJam")
                        .HasColumnType("float")
                        .HasColumnName("durasi_jam");

                    b.Property<string>("IdKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_kontrak");

                    b.Property<string>("JenisLayanan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jenis_layanan");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("SlaTerpenuhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sla_terpenuhi");

                    b.Property<DateTime>("TanggalKunjungan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_kunjungan");

                    b.HasKey("IdLog");

                    b.HasIndex("IdKontrak");

                    b.ToTable("monitoring_ltsa", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Padi", b =>
                {
                    b.Property<string>("IdPadi")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_padi");

                    b.Property<string>("Bagian")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bagian");

                    b.Property<string>("CatatanStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DokumenPendukung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dokumen_pendukung");

                    b.Property<string>("IdVendor")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_vendor");

                    b.Property<string>("JudulPembelian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("judul_pembelian");

                    b.Property<string>("LinkPembelian")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link_pembelian");

                    b.Property<decimal>("Nilai")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nilai");

                    b.Property<string>("NoPembelian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_pembelian");

                    b.Property<string>("NoPoPr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("no_po_pr");

                    b.Property<string>("StatusPurchase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_purchase");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<DateTime?>("TanggalBast")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_bast");

                    b.Property<DateTime?>("TanggalInvoice")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_invoice");

                    b.Property<DateTime?>("TanggalPaid")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_paid");

                    b.Property<DateTime?>("TanggalPaymentApproval")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_payment_approval");

                    b.Property<DateTime?>("TanggalSaGr")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_sa_gr");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdPadi");

                    b.HasIndex("IdVendor");

                    b.ToTable("padi", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.ProgressLumpsum", b =>
                {
                    b.Property<string>("IdProgress")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_progress");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("evidence");

                    b.Property<string>("IdKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_kontrak");

                    b.Property<string>("Milestone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("milestone");

                    b.Property<double>("Persen")
                        .HasColumnType("float")
                        .HasColumnName("persen");

                    b.Property<DateTime>("TanggalUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_update");

                    b.HasKey("IdProgress");

                    b.HasIndex("IdKontrak");

                    b.ToTable("progress_lumpsum", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.ProgressUnitPrice", b =>
                {
                    b.Property<string>("IdProgress")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_progress");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("HargaSatuan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("harga_satuan");

                    b.Property<string>("IdKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_kontrak");

                    b.Property<string>("NamaItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_item");

                    b.Property<double>("QtyAktual")
                        .HasColumnType("float")
                        .HasColumnName("qty_aktual");

                    b.Property<double>("QtyRencana")
                        .HasColumnType("float")
                        .HasColumnName("qty_rencana");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("satuan");

                    b.Property<DateTime>("TanggalUpdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_update");

                    b.HasKey("IdProgress");

                    b.HasIndex("IdKontrak");

                    b.ToTable("progress_unit_price", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Tagihan", b =>
                {
                    b.Property<string>("IdTagihan")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_tagihan");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DokumenMemo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dokumen_memo");

                    b.Property<string>("DokumenTagihan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dokumen_tagihan");

                    b.Property<string>("IdKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_kontrak");

                    b.Property<bool>("MemoRequired")
                        .HasColumnType("bit")
                        .HasColumnName("memo_required");

                    b.Property<decimal>("NilaiTagihan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nilai_tagihan");

                    b.Property<string>("NomorTagihan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomor_tagihan");

                    b.Property<string>("StatusTagihan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_tagihan");

                    b.Property<DateTime?>("TanggalPengirimanMemo")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_pengiriman_memo");

                    b.Property<DateTime>("TanggalTagihan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_tagihan");

                    b.Property<string>("Termin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("termin");

                    b.Property<string>("TipeKontrak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipe_kontrak");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTagihan");

                    b.HasIndex("IdKontrak");

                    b.ToTable("tagihan", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Vendor", b =>
                {
                    b.Property<string>("IdVendor")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_vendor");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alamat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("NamaVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_vendor");

                    b.Property<string>("Npwp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("npwp");

                    b.Property<string>("PicKontak")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pic_kontak");

                    b.Property<string>("PicNama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pic_nama");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<string>("StatusVendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status_vendor");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("IdVendor");

                    b.ToTable("vendor", (string)null);
                });

            modelBuilder.Entity("RefineryContractAPI.Models.AmandemenKontrak", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Kontrak", "Kontrak")
                        .WithMany("Amandemen")
                        .HasForeignKey("IdKontrak")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontrak");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Kontrak", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Vendor", "Vendor")
                        .WithMany("Kontraks")
                        .HasForeignKey("IdVendor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.MonitoringLtsa", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Kontrak", "Kontrak")
                        .WithMany("MonitoringLtsas")
                        .HasForeignKey("IdKontrak")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontrak");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Padi", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Vendor", "Vendor")
                        .WithMany("Padis")
                        .HasForeignKey("IdVendor");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.ProgressLumpsum", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Kontrak", "Kontrak")
                        .WithMany("ProgressLumpsums")
                        .HasForeignKey("IdKontrak")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontrak");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.ProgressUnitPrice", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Kontrak", "Kontrak")
                        .WithMany("ProgressUnitPrices")
                        .HasForeignKey("IdKontrak")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontrak");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Tagihan", b =>
                {
                    b.HasOne("RefineryContractAPI.Models.Kontrak", "Kontrak")
                        .WithMany("Tagihans")
                        .HasForeignKey("IdKontrak")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kontrak");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Kontrak", b =>
                {
                    b.Navigation("Amandemen");

                    b.Navigation("MonitoringLtsas");

                    b.Navigation("ProgressLumpsums");

                    b.Navigation("ProgressUnitPrices");

                    b.Navigation("Tagihans");
                });

            modelBuilder.Entity("RefineryContractAPI.Models.Vendor", b =>
                {
                    b.Navigation("Kontraks");

                    b.Navigation("Padis");
                });
#pragma warning restore 612, 618
        }
    }
}
